# Generated by Django 5.2.1 on 2025-05-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('accounts', 'Accounts'), ('hr', 'HR'), ('admin', 'Admin')], default='consumer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_control',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_range', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_timings', to='users.course')),
            ],
            options={
                'db_table': 'users_batch_timings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('training_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('reason_for_slot', models.TextField(blank=True)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('other', 'Other')], default='student', max_length=20)),
                ('highest_qualification', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor’s Degree'), ('master', 'Master’s Degree'), ('other', 'Other')], default='high_school', max_length=20)),
                ('experience_years', models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], default='0-1', max_length=10)),
                ('source_of_info', models.CharField(choices=[('social_media', 'Social Media'), ('friend', 'Friend'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='social_media', max_length=20)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('follow_up_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.batchtiming')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enquiry_data',
                'managed': True,
            },
        ),
    ]
