# Generated by Django 5.1.7 on 2025-06-30 16:23

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accesscontrol_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[users.models.validate_name])),
                ('phone_number', models.CharField(max_length=10, validators=[users.models.validate_phone_number])),
                ('email', models.EmailField(max_length=254, validators=[users.models.validate_gmail_email])),
                ('current_location', models.CharField(max_length=255)),
                ('course_enquiry', models.CharField(choices=[('Professional Starter Testing', 'Professional Starter Testing'), ('Professional Experts with Java Automation', 'Professional Experts with Java Automation'), ('Professional Experts with Python Automation', 'Professional Experts with Python Automation'), ('Professional Experts with Mobile Automation', 'Professional Experts with Mobile Automation'), ('Professional Experts with API Automation', 'Professional Experts with API Automation'), ('SDET Xpert', 'SDET Xpert'), ('Individual Courses', 'Individual Courses'), ('AI Testing', 'AI Testing'), ('Playwright', 'Playwright'), ('Cypress', 'Cypress'), ('Python Development Full Stack', 'Python Development Full Stack'), ('Java Full Stack Development', 'Java Full Stack Development'), ('MERN Stack', 'MERN Stack'), ('UI/UX Designing', 'UI/UX Designing'), ('AI/ML Engineering', 'AI/ML Engineering'), ('Data Analytics', 'Data Analytics'), ('Diploma in Software Engineering at Testing', 'Diploma in Software Engineering at Testing'), ('Diploma in Software Engineering at Development', 'Diploma in Software Engineering at Development'), ('Other', 'Other')], max_length=255)),
                ('training_mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('training_timing', models.CharField(choices=[('Morning (7AM Batch)', 'Morning (7AM Batch)'), ('Evening (8PM Batch)', 'Evening (8PM Batch)'), ('Anytime in Weekdays', 'Anytime in Weekdays'), ('Weekends', 'Weekends')], max_length=50)),
                ('start_time', models.CharField(choices=[('Immediate', 'Immediate'), ('After 10 days', 'After 10 days'), ('After 15 days', 'After 15 days'), ('After 1 Month', 'After 1 Month')], default='Immediate', max_length=50)),
                ('professional_situation', models.CharField(choices=[('Fresher', 'Fresher'), ('Currently Working', 'Currently Working'), ('Willing to Switch from Another Domain', 'Willing to Switch from Another Domain'), ('Other', 'Other')], max_length=100)),
                ('qualification', models.CharField(choices=[('Diploma', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Other', 'Other')], max_length=50)),
                ('experience', models.CharField(choices=[('Less than 1 Year or Fresher', 'Less than 1 Year or Fresher'), ('1-3 Years', '1-3 Years'), ('3-5 Years', '3-5 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('referral_source', models.CharField(choices=[('Instagram', 'Instagram'), ('WhatsApp Channel', 'WhatsApp Channel'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('Friend Reference', 'Friend Reference'), ('College Reference', 'College Reference'), ('Other Social Network', 'Other Social Network')], max_length=100)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batchtiming',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='role',
            field=models.CharField(choices=[('counsellor', 'Counsellor'), ('accounts', 'Accounts'), ('hr', 'HR'), ('admin', 'Admin'), ('consumer', 'Consumer')], default='counsellor', max_length=20),
        ),
        migrations.CreateModel(
            name='EnquiryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_module', models.CharField(max_length=255)),
                ('training_mode', models.CharField(max_length=20)),
                ('training_timing', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('calling1', models.CharField(blank=True, max_length=255, null=True)),
                ('calling2', models.CharField(blank=True, max_length=255, null=True)),
                ('calling3', models.CharField(blank=True, max_length=255, null=True)),
                ('calling4', models.CharField(blank=True, max_length=255, null=True)),
                ('calling5', models.CharField(blank=True, max_length=255, null=True)),
                ('move_to_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_list', to='users.studentenquiry')),
            ],
            options={
                'verbose_name_plural': 'Enquiry Lists',
            },
        ),
        migrations.CreateModel(
            name='DemoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[users.models.validate_name])),
                ('phone_number', models.CharField(max_length=10, validators=[users.models.validate_phone_number])),
                ('email', models.EmailField(max_length=254, validators=[users.models.validate_gmail_email])),
                ('package_code', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=100)),
                ('demo_class_status', models.CharField(choices=[('Not yet started', 'Not yet started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not yet started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentenquiry')),
            ],
            options={
                'verbose_name_plural': 'Demo Lists',
            },
        ),
    ]
