# Generated by Django 5.2.3 on 2025-07-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentenquiry_alter_accesscontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='highest_qualification',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('other', 'Other')], default='high_school', max_length=20),
        ),
    ]
