# Generated by Django 5.2.3 on 2025-07-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_consent_to_contact_enquiry_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirylist',
            name='student_enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_list', to='users.studentenquiry'),
        ),
    ]
