# Generated by Django 5.2.3 on 2025-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_enquirylist_student_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
