# Generated by Django 5.2.3 on 2025-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentenquiry_current_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='previous_interaction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
