# Generated by Django 5.2.3 on 2025-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_enquiry_previous_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='previous_interaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
