# Generated by Django 5.2.3 on 2025-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_enquiry_previous_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='move_to_acc',
            field=models.BooleanField(default=False),
        ),
    ]
