# Generated by Django 5.2.3 on 2025-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_enquiry_move_to_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='move_to_class',
            field=models.BooleanField(default=False),
        ),
    ]
