# Generated by Django 5.2.3 on 2025-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_enquiry_amountpaid_enquiry_balanceamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='pay_calling1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pay_calling2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pay_calling3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pay_calling4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pay_calling5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
