# Generated by Django 5.2.3 on 2025-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_enquiry_pay_calling1_enquiry_pay_calling2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='move_to_hr',
            field=models.BooleanField(default=False),
        ),
    ]
