# Generated by Django 5.2.3 on 2025-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_enquiry_move_to_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
