# Generated by Django 5.2.3 on 2025-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_enquiry_follow_up_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='data_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='data_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='move_to_placements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='placement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
