# Generated by Django 5.2.3 on 2025-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_enquiry_data_link_enquiry_data_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='details_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
